TestNode: treenode.h TestTreeNode.cpp
	g++ -Wall -g -std=c++11 -o TestNode TestTreeNode.cpp

TestTree: treenode.h tree.h TestTree.cpp
	g++ -Wall -g -std=c++11 -o TestTree TestTree.cpp

TestTreeMap: treenode.h tree.h treemap.h TestTreeMap.cpp
	g++ -Wall -g -std=c++11 -o TestTreeMap TestTreeMap.cpp


TestTreeD:  treenode.h tree.h TestTreeD.cpp
	g++ -Wall -g -std=c++11 -o TestTreeD TestTreeD.cpp

all: TestNode TestTree TestTreeMap TestTreeD
